// app/layout.js
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/utils/authOptions";
import DashboardLayout from "@/mainlayout/DashboardLayout";
import MainLayout from "@/mainlayout/MainLayout";

const jetbrainsMono = JetBrains_Mono({ 
  subsets: ["latin"], 
  weight: ["100","200","300","400","500","600","700","800"],
  variable: "--font-jetbrainsMono",
});

export const metadata = {
  title: "Resume of Rashadul Islam",
  description: "Generated by Md Rashadul Islam",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  // Check if the current route is a dashboard route
  const isDashboard = typeof window !== "undefined" && window.location.pathname.includes("dashboard");

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={jetbrainsMono.variable}>
        {isDashboard ? <DashboardLayout>{children}</DashboardLayout> : <MainLayout session={session}>{children}</MainLayout>}
      </body>
    </html>
  );
}
